### ISSUE TITLE
AttributeError: module 'corsair_scan' has no attribute 'corsair_scan'

### ISSUE THREAD

**Issue by MauroEldritch** [Santandersecurityresearch/corsair_scan#26]
* Corsair_scan version: latest
* Python version: Python 3.8.5
* Operating System: Debian 10

### Description

Trying to run the provided example, I receive the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/corsair", line 18, in <module>
    print (corsair_scan.corsair_scan(data, verify=True))
AttributeError: module 'corsair_scan' has no attribute 'corsair_scan'
```

Is there something I'm missing? Really curious to try your tool. Thanks.

### What I Did

Ran the provided example.

**Comment by javixeneize** [comment]
Hi! Thanks for opening the issue. This is one of the typical python errors :), looks like it can't resolve the module. 

Have you installed it as a dependency with pip, or are you just cloning the repo?

Thanks

**Comment by javixeneize** [comment]
Sin problema ;)

I see what is the problem... The module to import is corsair_scan.corsair_scan.

Just do the import like this

import corsair_scan.corsair_scan as corsair
.....

print (corsair.corsair_scan(data, verify=True))

Thanks for pointing out!

**Comment by MauroEldritch** [comment]
Works perfectly now, thanks for the support! 

Looking forward for the CLI release! 

Best,
Mauro

**Comment by javixeneize** [comment]
@MauroEldritch CLI has just been released :)
